### ISSUE TITLE
Line 13 on the json is advertising something completely different 

### ISSUE THREAD

**Issue by FuckingStealingNames** [PureEvil139/Bl2-Mods#1]
When inspecting this mod from the PySDK mod database, it states to "Add player scaling to Normal Mode and TVHM.", and going into the mod itself, it states to "Customize the size of your character’s backpack on the fly"

copied json from https://github.com/Rossays/BL-SDK-Mods/blob/main/modinfo.json#L15 ?

**Comment by PureEvil139** [comment]
Fixed the line thank you
